-- RUN THIS IN YOUR SUPABASE SQL EDITOR

create table if not exists scan_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  scanned_address text not null,
  scanner_id text,
  status text,
  timestamp text
);

-- Enable RLS (Optional but recommended)
alter table scan_logs enable row level security;

-- Policy: Allow Insert from Anon (or Service Role if you prefer, but Anon is used by client usually, though here we use server-side. 
-- If using server-side client with generic key, it might need policy or service_role key.
-- Since we are using Supabase Client in Node (likely service role or anon), let's just open read for now or assume service role bypasses RLS).

-- Allow read access to everyone (for Admin Dashboard later)
create policy "Enable read access for all users" on scan_logs for select using (true);

-- Allow insert access for all users (for now, to ensure scanner works)
create policy "Enable insert for all users" on scan_logs for insert with check (true);
